---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pdsw2935/public_html/PDStefanus
    - export DEPLOYPATH_public=/home/pdsw2935/public_html/PDStefanus/public
    - /bin/cp -R public/css $DEPLOYPATH_public
    - /bin/cp -R public/images $DEPLOYPATH_public
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH