---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pdsw2935/PDStefanus/
    - export DEPLOYPATH_CSS=/home/pdsw2935/public_html/css/
    - export DEPLOYPATH_IMAGES=/home/pdsw2935/public_html/images/
    - /bin/cp -R public/css $DEPLOYPATH_CSS
    - /bin/cp -R public/images $DEPLOYPATH_IMAGES
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH