name: Deploy Private GitHub repository to cPanel
on:
  push:
    branches:
      - master
jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: 📂 Sync folders and files to the server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
      - name: Update dependencies
        run: composer update --no-progress --no-suggest --prefer-dist
      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-progress --no-scripts
